# -*- coding: utf-8 -*-
"""φ⁴ Oscillon (real scalar)/Complex Higgs Field (amplitude + phase).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vgq-MEpU0_hibTYImgr2qXIDRkTVAFuV
"""

# === φ⁴ oscillon (real scalar) — Colab cell A ===
# Saves: phi4_oscillon_regenerated.mp4, phi_field_array.npy, energy_phi4.csv
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os, numpy as np, imageio, time
from scipy.ndimage import convolve, gaussian_filter
import matplotlib.pyplot as plt

# ---- Output folder in Drive ----
OUT_DIR = "/content/drive/My Drive/ImprintField_phi4_regen/"
os.makedirs(OUT_DIR, exist_ok=True)

# ---- Physical / numeric params ----
lambda_phi4 = 1.0
v = 1.0
c = 1.0                 # natural units
dx = 0.05
CFL = 0.35
dt = CFL * dx / c
n_steps = 1200          # total timesteps (increase to run longer)
save_every = 6          # save visualization frame every k steps

# ---- Grid (2D midplane evolution for speed) ----
N = 128
x = (np.arange(N)-N//2)*dx
y = (np.arange(N)-N//2)*dx
X,Y = np.meshgrid(x,y, indexing='ij')
R = np.sqrt(X*X + Y*Y)

# ---- Initial condition: long-lived oscillon gaussian ----
amp = 0.72 * v
width = 0.7
phi = amp * np.exp(-(R/width)**2)
prev_phi = phi.copy()

# ---- Laplacian kernel (5-point) ----
kernel = np.array([[0,1,0],
                   [1,-4,1],
                   [0,1,0]], dtype=np.float32)

# ---- Soft boundary damping (PML-ish) ----
pml = 12
damp = np.ones((N,N), dtype=np.float32)
for i in range(pml):
    f = ((i+1)/pml)**2
    damp[i,:] *= f; damp[-1-i,:] *= f
    damp[:,i] *= f; damp[:,-1-i] *= f

# ---- storage ----
frames = []
energies = []

print("Running φ⁴ oscillon:", n_steps, "steps, grid", N)

t0 = time.time()
for step in range(n_steps):
    lap = convolve(phi, kernel, mode='reflect') / (dx*dx)
    force = lambda_phi4 * phi * (phi*phi - v*v)
    new_phi = 2*phi - prev_phi + (c*dt)**2 * (lap - force)
    new_phi *= damp

    # update
    prev_phi, phi = phi, new_phi

    # energy (sampled)
    if (step % 20) == 0:
        grad_y, grad_x = np.gradient(phi, dx, axis=(0,1))
        kin = 0.5 * np.sum(((phi - prev_phi)/(2*dt))**2)
        grad = 0.5 * np.sum(grad_x**2 + grad_y**2)
        pot = 0.25 * lambda_phi4 * np.sum(phi**4 - 2*v*v*phi**2 + v**4)
        energies.append((step, kin, grad, pot, kin+grad+pot))

    # visualization frame
    if step % save_every == 0:
        # map phi from [-v,+v] to [0,1] for colormap
        img = (phi - (-v)) / (2*v)
        img = np.clip(img, 0.0, 1.0)
        rgba = plt.cm.RdBu_r(img)[:,:,:3]
        frame = (255 * rgba).astype(np.uint8)
        frames.append(frame)

    if step % 200 == 0:
        print(f"Step {step}/{n_steps}")

dt_total = time.time() - t0
print("Sim time:", dt_total, "s; frames:", len(frames))

# ---- save video ----
mp4_path = os.path.join(OUT_DIR, "phi4_oscillon_regenerated.mp4")
with imageio.get_writer(mp4_path, fps=25, codec='libx264', pixelformat='yuv420p') as w:
    for f in frames:
        w.append_data(f)
print("Saved video:", mp4_path)

# ---- save raw field array (T, Y, X) if needed (save reduced temporal sampling) ----
phi_stack = np.stack([ ( (f[:,:,0].astype(np.float32)/255.0)*2.0 - 1.0 ) for f in frames ])  # approximate inverse mapping
np.save(os.path.join(OUT_DIR,"phi_field_array.npy"), phi_stack)
print("Saved field array (approx):", os.path.join(OUT_DIR,"phi_field_array.npy"))

# ---- save energy log ----
import csv
energy_csv = os.path.join(OUT_DIR, "energy_phi4.csv")
with open(energy_csv, "w", newline='') as fh:
    writer = csv.writer(fh)
    writer.writerow(["step","kinetic","gradient","potential","total"])
    writer.writerows(energies)
print("Saved energy log:", energy_csv)

print("DONE. Check Drive folder:", OUT_DIR)

# === Complex Higgs field visualization — Colab cell B ===
# Saves: higgs_amplitude_phase.mp4, higgs_field_array.npy, energy_higgs.csv
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os, numpy as np, imageio, time
from scipy.ndimage import convolve
import matplotlib.pyplot as plt

# ---- Output folder ----
OUT_DIR = "/content/drive/My Drive/ImprintField_Higgs_visuals/"
os.makedirs(OUT_DIR, exist_ok=True)

# ---- Physical / numeric params ----
lambda_phi = 1.0
v = 1.0
c = 1.0
dx = 0.05
CFL = 0.28
dt = CFL * dx / c
n_steps = 800
save_every = 5

# ---- Grid (3D small volume, visualize midplane) ----
gx = gy = 96
gz = 32
x = (np.arange(gx)-gx//2)*dx
y = (np.arange(gy)-gy//2)*dx
z = (np.arange(gz)-gz//2)*dx
X,Y,Z = np.meshgrid(x,y,z, indexing='ij')
R = np.sqrt(X*X + Y*Y + Z*Z)

# ---- Initial complex field: localized amplitude + small random phase ----
amp0 = 0.7 * v
width = 0.7
rho0 = amp0 * np.exp(-(R/width)**2)
theta0 = 0.15 * np.random.randn(*R.shape)
phi1 = (rho0 * np.cos(theta0)).astype(np.float32)
phi2 = (rho0 * np.sin(theta0)).astype(np.float32)
prev1 = phi1.copy()
prev2 = phi2.copy()

# ---- Laplacian kernel (7-point in 3D) ----
kernel = np.zeros((3,3,3), dtype=np.float32)
kernel[0,1,1]=kernel[2,1,1]=kernel[1,0,1]=kernel[1,2,1]=kernel[1,1,0]=kernel[1,1,2]=1
kernel[1,1,1] = -6

# ---- PML damping near boundaries ----
pml = 10
damp = np.ones((gx,gy,gz), dtype=np.float32)
for i in range(pml):
    f = ((i+1)/pml)**2
    damp[i,:,:] *= f; damp[-1-i,:,:] *= f
    damp[:,i,:] *= f; damp[:,-1-i,:] *= f
    damp[:,:,i] *= f; damp[:,:,-1-i] *= f

# ---- force for Higgs (component-wise) ----
def higgs_force(p1, p2):
    r2 = p1*p1 + p2*p2
    fac = lambda_phi * (r2 - v*v)
    return fac * p1, fac * p2

# ---- storage ----
frames = []
energies = []

print("Running complex Higgs evolution:", n_steps, "steps; grid", gx,gy,gz)
tstart = time.time()
midz = gz//2

for step in range(n_steps):
    lap1 = convolve(phi1, kernel, mode='mirror') / (dx*dx)
    lap2 = convolve(phi2, kernel, mode='mirror') / (dx*dx)
    f1, f2 = higgs_force(phi1, phi2)

    new1 = 2*phi1 - prev1 + (c*dt)**2 * (lap1 - f1)
    new2 = 2*phi2 - prev2 + (c*dt)**2 * (lap2 - f2)

    # damping
    new1 *= damp
    new2 *= damp

    prev1, phi1 = phi1, new1
    prev2, phi2 = phi2, new2

    # energy sampling
    if step % 20 == 0:
        # approximate kinetic from finite diff
        kin = 0.5 * np.sum(((phi1 - prev1)/(2*dt))**2 + ((phi2 - prev2)/(2*dt))**2)
        gx1, gy1, gz1 = np.gradient(phi1, dx, axis=(0,1,2))
        gx2, gy2, gz2 = np.gradient(phi2, dx, axis=(0,1,2))
        grad = 0.5 * np.sum(gx1**2 + gy1**2 + gz1**2 + gx2**2 + gy2**2 + gz2**2)
        pot = 0.25 * lambda_phi * np.sum((phi1**2 + phi2**2 - v*v)**2)
        energies.append((step, kin, grad, pot, kin+grad+pot))

    # visualization frame (mid-z slice)
    if step % save_every == 0:
        A = np.sqrt(phi1[:,:,midz]**2 + phi2[:,:,midz]**2)   # amplitude
        PH = np.arctan2(phi2[:,:,midz], phi1[:,:,midz])     # phase [-pi,pi]
        # amplitude normalized
        A_norm = np.clip(A / (1.2*v), 0.0, 1.0)
        amp_rgb = plt.cm.RdBu_r(A_norm)[:,:,:3]
        PH_norm = (PH + np.pi) / (2*np.pi)
        phase_rgb = plt.cm.hsv(PH_norm)[:,:,:3]
        alpha = (A_norm**1.5)[:,:,None]
        combined = (1-alpha)*amp_rgb + alpha*phase_rgb
        frame = (255 * np.clip(combined, 0.0, 1.0)).astype(np.uint8)
        # annotate
        import cv2
        cv2.putText(frame, f"Higgs | step {step}", (10, frame.shape[0]-10), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255,255,255), 1, cv2.LINE_AA)
        frames.append(frame)

    if step % 200 == 0:
        print(f"Step {step}/{n_steps}")

tend = time.time()
print("Sim finished in", round(tend-tstart,2), "s; frames:", len(frames))

# ---- save video ----
mp4_path = os.path.join(OUT_DIR, "higgs_amplitude_phase.mp4")
with imageio.get_writer(mp4_path, fps=25, codec='libx264', pixelformat='yuv420p') as w:
    for f in frames:
        w.append_data(f)
print("Saved Higgs video:", mp4_path)

# ---- save compressed field arrays (take a few snapshots to reduce size) ----
# stack a subsampled set of midplane amplitudes for quick reference
field_stack = np.stack([ np.sqrt(phi1[:,:,midz]**2 + phi2[:,:,midz]**2) for i in range(len(frames)) ])
np.save(os.path.join(OUT_DIR, "higgs_field_array.npy"), field_stack)
print("Saved higgs field array (midplane):", os.path.join(OUT_DIR,"higgs_field_array.npy"))

# ---- save energy log ----
import csv
energy_csv = os.path.join(OUT_DIR, "energy_higgs.csv")
with open(energy_csv, "w", newline='') as fh:
    writer = csv.writer(fh)
    writer.writerow(["step","kinetic","gradient","potential","total"])
    writer.writerows(energies)
print("Saved energy log:", energy_csv)

print("DONE. Files in Drive folder:", OUT_DIR)

from google.colab import files

osc_path = "/content/drive/My Drive/ImprintField_phi4_regen/phi4_oscillon_regenerated.mp4"

print("Downloading:", osc_path)
files.download(osc_path)

from google.colab import files

higgs_path = "/content/drive/My Drive/ImprintField_Higgs_visuals/higgs_amplitude_phase.mp4"

print("Downloading:", higgs_path)
files.download(higgs_path)

# --- φ⁴ Oscillon Diagnostic Analysis with Stability Classification (improved) ---
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter1d
from scipy.fft import rfft, rfftfreq
import pandas as pd
from tqdm import tqdm

# -------- Configuration --------
video_path = "/content/drive/My Drive/ImprintField_phi4_visuals/phi4_mode2C_cinematic.mp4"
v = 1.0
fps_override = None  # set to float to override fps from file, else None
resize_max_dim = 512  # set None to keep original resolution; reduces FFT cost if big
use_roi_centroid = True  # if True, estimate core centroid each frame for center_phi
out_csv = "/content/drive/My Drive/ImprintField_phi4_visuals/phi_diagnostics_summary.csv"
out_plot = "/content/drive/My Drive/ImprintField_phi4_visuals/phi_diagnostics_plot.png"
save_plots = True

# -------- Sanity checks --------
if not os.path.exists(video_path):
    raise FileNotFoundError(f"Video not found: {video_path}")

cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    raise RuntimeError("Failed to open video. Check file/permissions.")

# Prefer reported frame count, but fall back to reading frames loop if unavailable
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) or None
fps = fps_override or (cap.get(cv2.CAP_PROP_FPS) or 25.0)

# If frame_count is available, pre-allocate a list capacity hint (Python list cannot pre-size)
frames = []

print(f"Opening video: {video_path}")
print(f"Reported FPS: {fps:.2f}, Reported frame count: {frame_count}")

# --- Load frames (grayscale); optionally resize to speed processing ---
read_iter = range(frame_count) if frame_count else iter(int, 1)
pbar = tqdm(total=frame_count if frame_count else None, desc="Reading frames")
while True:
    ret, frame = cap.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    if resize_max_dim is not None:
        h, w = gray.shape
        max_dim = max(h, w)
        if max_dim > resize_max_dim:
            scale = resize_max_dim / max_dim
            new_w, new_h = int(w * scale), int(h * scale)
            gray = cv2.resize(gray, (new_w, new_h), interpolation=cv2.INTER_AREA)
    frames.append(gray.astype(np.float32))
    pbar.update(1)
pbar.close()
cap.release()

if len(frames) == 0:
    raise RuntimeError("No frames were read from the video.")

frames = np.stack(frames)  # shape (T, H, W)
T, H, W = frames.shape
print(f"🎥 Loaded video: {T} frames, resolution {H}x{W}")

# --- Brightness → φ mapping (0→−v, 255→+v) ---
phi_frames = (frames / 255.0) * 2.0 * v - v

# Preallocate metric arrays
center_phi = np.zeros(T, dtype=np.float64)
spatial_var = np.zeros(T, dtype=np.float64)
core_frac = np.zeros(T, dtype=np.float64)
energy_proxy = np.zeros(T, dtype=np.float64)
highk_power = np.zeros(T, dtype=np.float64)

# Precompute k-radius grid for FFT masking (uses shifted indices)
ny, nx = H, W
yy, xx = np.mgrid[-ny//2:(ny//2 + ny%2), -nx//2:(nx//2 + nx%2)]
kr_grid = np.sqrt(xx**2 + yy**2)
# threshold in pixel-frequency units (tuneable)
highk_thresh = 0.25 * max(nx, ny)

# Optional ROI centroid initial guess (center of frame)
cy0, cx0 = H // 2, W // 2
roi_radius = int(min(H, W) * 0.25)  # region to compute centroid within (25% of smaller dim)

for t in range(T):
    phi = phi_frames[t]
    spatial_var[t] = np.var(phi)

    # Core fraction: fraction of pixels with |phi| > threshold
    core_frac[t] = np.mean(np.abs(phi) > 0.6 * v)

    # Center phi — either frame center or centroid of high-|phi| region (more robust)
    if use_roi_centroid:
        # mask around previous center to find core; thresholding helps ignore background
        y0, x0 = cy0, cx0
        y1, y2 = max(0, y0 - roi_radius), min(H, y0 + roi_radius)
        x1, x2 = max(0, x0 - roi_radius), min(W, x0 + roi_radius)
        sub = phi[y1:y2, x1:x2]
        # find centroid of strong-field pixels (abs phi above 0.6v)
        mask = np.abs(sub) > 0.6 * v
        if mask.sum() > 5:
            coords = np.argwhere(mask)
            mean_rel = coords.mean(axis=0)  # (ry, rx)
            cy0 = int(y1 + mean_rel[0])
            cx0 = int(x1 + mean_rel[1])
        # fallback to center if centroid unstable
    cy, cx = cy0, cx0
    # Clip indices
    cy = np.clip(cy, 0, H - 1)
    cx = np.clip(cx, 0, W - 1)
    center_phi[t] = phi[cy, cx]

    # Energy proxy: gradient energy + potential
    gy, gx = np.gradient(phi)  # gy: d/dy, gx: d/dx
    grad2 = 0.5 * (gx**2 + gy**2)
    pot = 0.25 * (phi**2 - v**2)**2
    energy_proxy[t] = np.sum(grad2 + pot)

    # Spectrum & high-k power fraction (use shifted FFT so kr_grid aligns)
    F = np.fft.fftshift(np.fft.fft2(phi))
    P = np.abs(F) ** 2
    total_power = np.sum(P) + 1e-12
    highk_power[t] = np.sum(P[kr_grid > highk_thresh]) / total_power

# --- Smooth for clarity ---
center_s = gaussian_filter1d(center_phi, sigma=2)
var_s = gaussian_filter1d(spatial_var, sigma=2)
core_s = gaussian_filter1d(core_frac, sigma=2)
E_s = gaussian_filter1d(energy_proxy, sigma=2)
hk_s = gaussian_filter1d(highk_power, sigma=2)
t_axis = np.arange(T) / fps

# --- Plot metrics ---
plt.figure(figsize=(14, 9))
plt.subplot(3, 2, 1)
plt.plot(t_axis, center_s)
plt.title("Central φ(t)")
plt.grid(alpha=0.3)

plt.subplot(3, 2, 2)
plt.plot(t_axis, var_s)
plt.title("Spatial Variance")
plt.grid(alpha=0.3)

plt.subplot(3, 2, 3)
plt.plot(t_axis, core_s)
plt.title("Core Volume Fraction |φ|>0.6v")
plt.grid(alpha=0.3)

plt.subplot(3, 2, 4)
plt.plot(t_axis, E_s)
plt.title("Energy Proxy (Σ|∇φ|² + V(φ))")
plt.grid(alpha=0.3)

plt.subplot(3, 2, 5)
plt.plot(t_axis, hk_s)
plt.title("High-k Power Fraction")
plt.xlabel("Time (s)")
plt.grid(alpha=0.3)

plt.subplot(3, 2, 6)
# show small histogram of center phi
plt.hist(center_s, bins=40)
plt.title("Histogram: central φ")
plt.tight_layout()
if save_plots:
    plt.savefig(out_plot, dpi=200)
    print(f"Saved plot to: {out_plot}")
plt.show()

# --- Frequency analysis of central φ(t) ---
sig = center_s - np.mean(center_s)
sig_std = np.std(sig) + 1e-12
sig /= sig_std

# rfft-based spectrum
freqs = rfftfreq(T, d=1.0 / fps)
spectrum = np.abs(rfft(sig))
# ignore the zero-frequency bin when selecting peak; also avoid spurious tiny peaks
if spectrum.sum() < 1e-6:
    dominant_freq = 0.0
else:
    # find peak in a physically relevant band, e.g. >0.05 Hz and < fps/2
    valid = (freqs > 0.05) & (freqs < (fps / 2.0))
    if valid.any():
        idx = np.argmax(spectrum[valid])
        dominant_freq = freqs[valid][idx]
    else:
        dominant_freq = freqs[np.argmax(spectrum[1:]) + 1]

print(f"Dominant oscillation frequency: {dominant_freq:.4f} Hz (visual breathing rate)")

# --- Stability classification ---
def classify_stability(core, hk, energy):
    # Use safe denominators
    e0 = max(np.abs(energy[0]), 1e-9)
    drift_energy = (energy[-1] - energy[0]) / e0
    drift_core = (core[-1] - core[0])
    hk_mean = float(np.mean(hk[-min(10, len(hk)):]))
    # rules (tunable)
    if abs(drift_energy) < 0.05 and hk_mean < 0.05:
        return "🟢 Stable & Coherent Oscillon"
    elif drift_core < -0.05 or hk_mean > 0.12:
        return "🔴 Radiating / Decaying"
    else:
        return "🟡 Quasi-stable or weakly radiating"

stability = classify_stability(core_s, hk_s, E_s)
print(f"\n🔍 Stability Assessment: {stability}")

# --- Save diagnostics to CSV ---
df = pd.DataFrame({
    "time_s": t_axis,
    "center_phi": center_phi,
    "center_phi_sm": center_s,
    "spatial_var": spatial_var,
    "spatial_var_sm": var_s,
    "core_frac": core_frac,
    "core_frac_sm": core_s,
    "energy_proxy": energy_proxy,
    "energy_proxy_sm": E_s,
    "highk_power": highk_power,
    "highk_power_sm": hk_s
})
# ensure output dir exists
os.makedirs(os.path.dirname(out_csv), exist_ok=True)
df.to_csv(out_csv, index=False)
print(f"📊 Saved detailed diagnostics: {out_csv}")